
// Extensión Paste JSON as Code
// https://pokeapi.co/
// Generated by https://quicktype.io   => app web para generar appis

//* Ir a pokeapi y copiar json CTRL + C
//* Venir acá y CTRL + V
//* CTRL + SHIFT + P (Command Palette)
//* Seleccionar Paste JSON as Code + enter


//! la extensión nos permite copy+paste un json (se mantiene mejor el texto y solo hacer pequeños ajustes)



